name: library-application-exam

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js -v
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build application
      run: npm install
    - name: Start application
      run: npm start &
    - name: Test the application
      run: npm run test:unit
    - run: Display SoftUni username Martin13s18