name: library-application-exam

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js -v
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build application
      uses: npm install
    - name: Start application
      uses: npm start
    - name: Run unit tests
      uses: npm run test:unit
    - name: Display SoftUni username
      uses: echo Martin13s18
      
